
services:
  frontend:
    build:
      context: ./FrontEnd
    ports:
      - "3000:3000"
    depends_on:
      - middle_api
    networks:
      - myinternalnetwork
    
  middle_api:
    build:
      context: ./my_middle_API
    ports:
      - "8000:8000"
    volumes:
      - ./my_middle_API/Backend/storage:/app/Backend/storage
    networks:
      - myinternalnetwork

  nginx:
    container_name: rvrs_prxy
    build:
      context: ./Nginx  # Directory containing the Dockerfile and configuration files
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - middle_api
    networks:
      - myinternalnetwork

networks:
  myinternalnetwork:
