version: '3.8'  # Specify the version of Docker Compose

services:
  frontend:
    build:
      context: ./FrontEnd
    ports:
      - "3000:3000"
    volumes:
      - ./FrontEnd:/app
      - /app/node_modules
    depends_on:
      - middle_api
    networks:
      - myinternalnetwork
    command: npm start  # Or the command you use to start your React app
    
  middle_api:
    build:
      context: ./my_middle_API
    ports:
      - "8000:8000"
    networks:
      - myinternalnetwork

  nginx:
    container_name: rvrs_prxy
    build:
      context: ./Nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - middle_api
    networks:
      - myinternalnetwork

networks:
  myinternalnetwork:
    driver: bridge
